GET http://localhost:3333/getClientes

###

POST http://localhost:3333/cadastroClientes
Content-Type: application/json

{
    "plano_idplano": 16,
    "nome": "Mateus Braga",
    "sexo": "m",
    "nascimento": "2002-12-27",
    "cpf": "12270917456",
    "telefone": "81991342744",
    "email": "mateus@gmail.com",
    "senha": "123456"
}

###
POST http://localhost:3333/getLogin
Content-Type:  application/json

{
    "email": "pedro@email.com",
    "senha": "senha1234"
}
###
GET http://localhost:3333/planos 

###
POST http://localhost:3333/recuperarUsuario
Content-Type: application/json

{
    "token": "27"
}

###

POST http://localhost:3333/cadastroFuncionarios
Content-Type: application/json

{
    "nome": "Mateus Braga",
    "sexo": "m",
    "nascimento": "2002-12-27",
    "cpf": "12270917456",
    "telefone": "81991342744",
    "email": "mateus@gmail.com",
    "senha": "123456",
    "cargo": "atendente",
    "salario": "800",
    "dataAdmissao": "2020-08-18",
    "dataPagamento": "2020-08-18"
}

###

POST http://localhost:3333/listarDataCliente
Content-Type: application/json

{
    "dataInit": "2020-01-01",
    "dataFim": "2023-01-01"
}

###
GET http://localhost:3333/financeiro 

###
GET http://localhost:3333/listaCliente?search=Diego  

###
POST http://localhost:3333/cadastroModalidade
Content-Type: application/json

{
    "nome": "jiu-jitsu",
    "descricao": "Estilo de luta que visa a imobilização"
}

###
DELETE http://localhost:3333/apagarUsuario
Content-Type: application/json

{
    "idPessoa": "789"
}

###
POST http://localhost:3333/editarCliente
Content-Type: application/json

{
    "idpessoa": "10",
    "nome": "Josimar Junior",
    "sexo": "m",
    "nascimento": "2003-11-23",
    "cpf": "11111111111",
    "email": "josimarjunior.cg@gmail.com",
    "telefone": "888888888",
    "senha": "junior123",
}

###
POST http://localhost:3333/editarFuncionario
Content-Type: application/json

{
    "idpessoa": "22",
    "nome": "Rainha da Caximbinha",
    "sexo": "f",
    "nascimento": "2000-10-10",
    "cpf": "11131112111",
    "email": "caximbinha@gmail.com",
    "telefone": "888778888",
    "senha": "caxumba",
    "cargo": "atendente",
    "salario": "800",
    "dataAdmissao": "2020-10-10",
    "dataPagamento": "2020-10-10"
}

###
GET http://localhost:3333/modalidades 

###
POST http://localhost:3333/criarPlanos
Content-Type: application/json

{
    "tipo": "testeBafo",
    "valor": "90",
    "desconto": "5",
    "modalidades": ["1", "2", "3"]
}

###
GET http://localhost:3333/planosVencidos

###
POST http://localhost:3333/renovarMatricula
Content-Type: application/json

{
    "idPlano": "9",
    "idCliente": "124",
    "formaPagamento": "Boleto Bancário",
    "dataPagamento": "2023-04-16"
}

###
GET http://localhost:3333/listaCliente 